# Generated by Django 2.0.7 on 2018-07-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown', models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14)),
                ('unencrypted_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(help_text='Name of file being stored', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='filesecret_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown', models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14)),
                ('unencrypted_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('data', models.TextField()),
                ('label', models.CharField(help_text='Human readable label', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='textsecret_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UPSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown', models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14)),
                ('unencrypted_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=32)),
                ('label', models.CharField(help_text='Human readable label', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='upsecret_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='upsecret',
            unique_together={('owner', 'label', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='textsecret',
            unique_together={('owner', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='filesecret',
            unique_together={('owner', 'filename')},
        ),
    ]
