# Generated by Django 2.0.7 on 2018-07-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesecret',
            name='display_data',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
    ]
