# Generated by Django 2.0.7 on 2018-07-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesecret',
            name='countdown',
            field=models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14),
        ),
        migrations.AddField(
            model_name='textsecret',
            name='countdown',
            field=models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14),
        ),
        migrations.AddField(
            model_name='upsecret',
            name='countdown',
            field=models.IntegerField(choices=[(1, 1), (7, 7), (14, 14), (30, 30), (60, 60), (90, 90)], default=14),
        ),
    ]
