# Generated by Django 2.0.7 on 2018-07-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_store', '0002_auto_20180728_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesecret',
            name='unencrypted_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textsecret',
            name='unencrypted_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upsecret',
            name='unencrypted_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
