# Generated by Django 2.0.7 on 2018-07-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_store', '0003_auto_20180729_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesecret',
            old_name='display_data',
            new_name='_display_data',
        ),
    ]
